apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hot
  template:
    metadata:
      labels:
        app: hot
    spec:
      containers:
      - image: okteto.dev/hot:latest
        name: hot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "cefcf589-bd14-42d1-a9af-09ec4884e64d"
        - name: Vless_Path
          value: "/d123"
        - name: Vmess_UUID
          value: "cefcf589-bd14-42d1-a9af-09ec4884e64d"
        - name: Vmess_Path
          value: "/d244"
        - name: Share_Path
          value: "share233"
